python_stack/django/level2/multiple_apps/apps/gold/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^process/(?P<location>[a-z]+)$', views.process, name='process'),
	url(r'^save$', views.save, name='save'),
	url(r'^show$', views.show, name='show'),
]

python_stack/django/level2/multiple_apps/apps/user_management/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^users$', views.create, name='create'),
	url(r'^login$', views.login, name='login'),
	url(r'^success$', views.success, name='success'),
	url(r'^logout$', views.logout, name='logout'),
]

python_stack/django/level2/multiple_apps/multiple_apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.user_management.urls', namespace="user_management")),
    url(r'^', include('apps.gold.urls', namespace="gold")),
]

python_stack/django/level2/multiple_apps/apps/gold/models.py
from __future__ import unicode_literals

from django.db import models

from ..user_management.models import User

# Create your models here.
class LeaderboardManager(models.Manager):
	def save_game(self, data):
		score = int(data['score'])
		user_id = int(data['user_id'])
		#try pulling a user
		try:
			cur_user = User.objects.get(id=user_id)
			#try pulling their board
			try:
				board = self.get(user=cur_user)
				print "got board"
				if board.top_score < score:
					board.top_score = score
				board.games_played += 1
				board.total_gold_earned += score
				board.save()
			#if there is no board
			except:
				print "making new board"
				board = self.create(
					user = cur_user,
					top_score = score,
					games_played = 1,
					total_gold_earned = score,
				)
				print "New Board!!!"
			return "Your top score is {}!".format(board.top_score)
		except:
			return "Oops, it looks like there's no user by your name!"

class Leaderboard(models.Model):
	user = models.OneToOneField(User)
	top_score = models.IntegerField()
	games_played = models.IntegerField()
	total_gold_earned = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = LeaderboardManager()

python_stack/django/level2/multiple_apps/apps/user_management/models.py
from __future__ import unicode_literals
from django.db import models

import re
import bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
	#define user creation for use in other models functions
	def create_user(self, first, last, email, pw_hash):
		user = self.create(first_name=first, last_name=last, email=email, pw_hash=pw_hash)
		return user

	def hash_password(self, password):
		password = password.encode()
		hashed_pw = bcrypt.hashpw(password, bcrypt.gensalt())
		# print hashed_pw
		return hashed_pw

	def login_check(self, data):
		#initialize error handler
		errors=[]
		#unpack data
		email = data['email']
		password = data['password'].encode()
		#run validations
		try:
			user = self.get(email=email)
			hashed_pw = user.pw_hash.encode()
			if bcrypt.hashpw(password, hashed_pw) == hashed_pw:
				return (True, user)
		except:
			errors.append("Incorrect email or password")
		
		return (False, errors)

	def validate_and_add(self, data):
		#initialize error handler
		errors = []
		#unpack data
		first = data['first-name']
		last = data['last-name']
		email = data['email']
		password = data['password']
		confirm = data['confirm']
		#run validations
		if len(first) < 2:
			errors.append("Please enter a first name.")
		elif not first.isalpha():
			errors.append("Please enter a valid first name.")
		if len(last) < 2:
			errors.append("Please enter a last name.")
		elif not last.isalpha():
			errors.append("Please enter a valid last name.")
		if len(email) < 1:
			errors.append("Please enter an email address.")
		elif not EMAIL_REGEX.match(email):
			errors.append("Please enter a valid email address.")
		if len(password) < 8:
			errors.append("Please enter a valid password.")
		elif password != confirm:
			errors.append("Passwords must match")

		if not errors:
			#Once form is validated, check to see if user exists.
			try:
				matches = self.get(email=email)
				errors.append("A user already exists with that email.")
				return (False, errors)
			except:
				#if all else passes hash password
				pw_hash = self.hash_password(data['password'])
				#create user with hashed password
				user = self.create_user(data['first-name'], data['last-name'], data['email'], pw_hash)
				return (True, user)
		else:
			print "triggered w/errors"
			return (False, errors)


class User(models.Model):
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	pw_hash = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

python_stack/django/level2/multiple_apps/apps/gold/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

import random, datetime
from .models import Leaderboard

# Create your views here.
def index(request):
	if 'activities' not in request.session:
		request.session['activities'] = []
	if 'gold_count' not in request.session:
		request.session['gold_count'] = 0
	return render(request, 'gold/index.html')

def process(request, location):
	if request.method == "POST":
		if 'gold_count' not in request.session:
			request.session['gold_count'] = 0
		if 'activities' not in request.session:
			request.session['activities'] = []

		locations = {
			"farm": ("won", random.randint(10, 20)),
			"cave": ("won", random.randint(5, 10)),
			"house": ("won", random.randint(2, 5)),
			"casino": ["", random.randint(-50, 50)],
		}

		for key, value in locations.items():
			if location == key:
				request.session['gold_count'] += value[1]
				if location == "casino":
					locations['casino'][0] = "won" if locations['casino'][1] >= 0 else "lost"
					if locations['casino'][0] == "won":
						exclam = "Nice"
						outcome = 1
					else:
						exclam = "Ouch"
						outcome = 0
					casino_str = "Entered the casino and {} {} golds... {}... {}".format(locations['casino'][0], locations['casino'][1], exclam, datetime.datetime.now())
					request.session['activities'].insert(0, (outcome, casino_str))
				else:
					outcome = 1
					string = "Earned {} golds from the {}! {}".format(value[1], location, datetime.datetime.now())
					request.session['activities'].insert(0, (outcome, string))
	return redirect(reverse('gold:index'))

def save(request):
	if request.method == "POST" and request.session['user_id']:

		data = {
			"score": request.session['gold_count'],
			"user_id": request.session['user_id'],
		}

		response = Leaderboard.objects.save_game(data)
		request.session['gold_count'] = 0
		request.session['activities'] = []

		messages.success(request, response)
	else:
		messages.error(request, "Oops! Something went wrong! Are you logged in?")
	return redirect(reverse('gold:index'))

def show(request):
	context = {
		'leaderboards': Leaderboard.objects.all().order_by('-top_score')[:15]
	}
	return render(request, 'gold/leaderboard.html', context)

python_stack/django/level2/multiple_apps/apps/user_management/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse

from .models import User
# Create your views here.
def index(request):
	return render(request, 'user_management/index.html')

def success(request):
	return render(request, 'user_management/success.html')

def create(request):
	if request.method == "POST":
		valid, response = User.objects.validate_and_add(request.POST)
		if valid:
			messages.success(request, "Hello {} {}!".format(response.first_name, response.last_name))
			request.session['user_id'] = response.id
			return redirect(reverse('gold:index'))
		else:
			for error in response:
				messages.error(request, error)

	return redirect(reverse('user_management:index'))

def login(request):
	if request.method == "POST":
		valid, response = User.objects.login_check(request.POST)
		if valid:
			messages.success(request, "Hello {} {}, thanks for logging in!".format(response.first_name, response.last_name))
			request.session['user_id'] = response.id
			return redirect(reverse('gold:index'))
		else:
			for error in response:
				messages.error(request, error)
	
	return redirect(reverse("user_management:index"))

def logout(request):
	request.session.clear()
	return redirect(reverse('gold:index'))

python_stack/django/level2/multiple_apps/apps/gold/templates/gold/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Ninja Gold!</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'gold/css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'gold/css/skeleton.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'gold/css/styles.css' %}">
</head>
<body>
	{% if request.session.user_id %}
		<h5>Welcome to Ninja Gold!</h5>
		{% if messages %}
			{% for message in messages %}
				<p>{{ message }}</p>
			{% endfor %}
		{% endif %}
		<a href="{% url 'user_management:logout' %}" class="button">Logut</a>
		<form id="save-button" name="save-game" action="{% url 'gold:save' %}" method="post">
			{% csrf_token %}
			<input type="submit" value="Save Game">
		</form>
	{% else %}
		<h5>Welcome to Ninja Gold! Login to save your score!</h5>
		<a href="{% url 'user_management:index' %}" class="button">Login or Register</a>
	{% endif %}
	<a href="{% url 'gold:show' %}" class="button">Check out the leaderboard</a>
	<div id="counter">
		<h2>Your Gold:</h2>
		<p>{{ request.session.gold_count }}</p>
	</div>
	<div class="location-box">
		<h2>Farm</h2>
		<p>(earns 10-20 golds)</p>
		<form action="/process/farm" method="post">
			{% csrf_token %}
			<input type="submit" value="Find Gold!"/>
		</form>
	</div>
	<div class="location-box">
		<h2>Cave</h2>
		<p>(earns 5-10 golds)</p>
		<form action="/process/cave" method="post">
			{% csrf_token %}
			<input type="submit" value="Find Gold!"/>
		</form>
	</div>
	<div class="location-box">
		<h2>House</h2>
		<p>(earns 2-5 golds)</p>
		<form action="/process/house" method="post">
			{% csrf_token %}
			<input type="submit" value="Find Gold!"/>
		</form>
	</div>
	<div class="location-box">
		<h2>Casino</h2>
		<p>(earns/takes 0-50 golds)</p>
		<form action="/process/casino" method="post">
			{% csrf_token %}
			<input type="submit" value="Find Gold!"/>
		</form>
	</div>
	<div id="activities">
		<p>Activities:</p>
		<div id="activities-list">
			{% if request.session.activities %}
				{% for item in request.session.activities %}
					{% if item.0 == 1 %}
						<p class="win">{{ item.1 }}</p>
					{% else %}
						<p class="loss">{{ item.1 }}</p>
					{% endif %}
				{% endfor %}
			{% endif %}
		</div>
	</div>
</body>
</html>

python_stack/django/level2/multiple_apps/apps/gold/templates/gold/leaderboard.html
<!DOCTYPE html>
<html>
<head>
	<title>Ninja Gold!</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'gold/css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'gold/css/skeleton.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'gold/css/styles.css' %}">
</head>
<body>
{% for item in leaderboards %}
	<li>User: {{ item.user.first_name }} {{ item.user.last_name }}, Top Score: {{ item.top_score }}, Games Played: {{ item.games_played }}, Lifetime Earnings: {{ item.total_gold_earned }}</li>
{% empty %}
<h2>Looks like no one has saved a game yet!</h2>
{% endfor %}
<a href="{% url 'gold:index' %}" class="button">Back to game</a>
</body>
</html>