python_stack/django/level2/belt_reviewer/apps/user_management/urls.py
from django.conf.urls import url
from . import views

app_name = "user_management"

urlpatterns = [
	url(r'^$', views.create, name='create'),
	url(r'^new$', views.index, name='index'),
	url(r'^(?P<user_id>\d+)$', views.show, name='show'),
	url(r'^login$', views.login, name='login'),
	url(r'^logout$', views.logout, name='logout'),
]

python_stack/django/level2/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.user_management.urls', namespace="user_management")),
    url(r'^', include('apps.book_review.urls', namespace="book_review")),
]

python_stack/django/level2/belt_reviewer/apps/user_management/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Count

import re
import bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
	def create_user(self, alias, first, last, email, pw_hash):
		user = self.create(
			alias=alias,
			first_name=first,
			last_name=last,
			email=email,
			pw_hash=pw_hash
		)
		return user

	def hash_password(self, password):
		password = password.encode()
		hashed_pw = bcrypt.hashpw(password, bcrypt.gensalt())
		return hashed_pw

	def compare_passwords(self, user, password):
		password = password.encode()
		hashed_pw = user.pw_hash.encode()
		if bcrypt.hashpw(password, hashed_pw) == hashed_pw:
			return True
		else:
			return False

	def validate_and_register(self, data):
		#unpack data
		alias = data['alias']
		first = data['first-name']
		last = data['last-name']
		email = data['email']
		password = data['password']
		confirm = data['confirm']
		#initialize error handler
		errors = []
		#run form validations
		if len(alias) < 1:
			errors.append('Please enter an alias')
		elif not alias.isalpha():
			errors.append('Alias must contain only letters, sorry!')
		if len(first) < 1:
			errors.append('Please enter a first name')
		elif not first.isalpha():
			errors.append('First name must contain only letters, sorry!')
		if len(last) < 1:
			errors.append('Please enter a last name')
		elif not last.isalpha():
			errors.append('Last name must contain only letters, sorry!')
		if len(email) < 1:
			errors.append('Please enter an email address')
		elif not EMAIL_REGEX.match(email):
			errors.append('Please enter a valid email address')
		if len(password) < 8:
			errors.append('Password must be at least 8 characters')
		elif password != confirm:
			errors.append("Passwords don't match")
		#break out if there are errors
		if errors:
			return (False, errors)

		try:
			match = self.get(email=email)
			errors.append("A user already exists with that email, please login or sign up with a new email.")
			return (False, errors)
		except:
			#once every check passes, hash password
			pw_hash = self.hash_password(password)
			#once password is hashed, create user
			user = self.create_user(alias, first, last, email, pw_hash)
			return (True, user)

	def login_check(self, data):
		#unpack data
		email = data['email']
		password = data['password']
		#initialize error handler
		errors = []
		try:
			user = self.get(email=email)
			if self.compare_passwords(user, password):
				return (True, user)
		except:
			errors.append("Incorrect email or password")

		return(False, errors)

	def get_user_info(self, user_id):
		from ..book_review.models import Book
		user_id = int(user_id)
		try:
			user = self.get(id=user_id)
			print "got user"
			user_reviews = User.objects.filter(id=user_id).annotate(num=Count('user_review'))
			print user_reviews[0].num
			books = Book.objects.filter(book_review__review_user=user)
			print books
			# reviews = Review.objects.filter(review_user=user).annotate(num=Count('id'))
			response = {
				'alias': user.alias,
				'first_name': user.first_name,
				'last_name': user.last_name,
				'email': user.email,
				'total_reviews': user_reviews[0].num,
				'books': books,
			}
			return (True, response)
		except:
			errors = "There was a problem loading this user."
			return (False, errors)

class User(models.Model):
	alias = models.CharField(max_length=255)
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	pw_hash = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

python_stack/django/level2/belt_reviewer/apps/user_management/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse

from .models import User
# Create your views here.
def index(req):
	return render(req, 'user_management/index.html')

def create(req):
	if req.method == "POST":
		valid, res = User.objects.validate_and_register(req.POST)
		if valid:
			req.session['user_id'] = res.id
			req.session['alias'] = res.alias
			return redirect(reverse('book_review:index'))
		else:
			for error in res:
				messages.error(req, error)
	else:
		messages.error(req, "Oops! Something went wrong!")
	return redirect(reverse('user_management:index'))

def show(req, user_id):
	valid, res = User.objects.get_user_info(user_id)
	if valid:
		context = {
			"user_info": res,
		}
	else:
		messages.error(req, res)
		return render(req, 'user_management/user_details.html')
	return render(req, 'user_management/user_details.html', context)

def login(req):
	if req.method == "POST":
		valid, res = User.objects.login_check(req.POST)
		if valid:
			req.session['user_id'] = res.id
			req.session['alias'] = res.alias
			print req.session['alias']
			return redirect(reverse('book_review:index'))
		else:
			for error in res:
				messages.error(req, error)
	else:
		messages.error(req, "Oops! Something went wrong!")
	return redirect(reverse('user_management:index'))

def logout(req):
	req.session.clear()
	return redirect(reverse('book_review:index'))

python_stack/django/level2/belt_reviewer/apps/user_management/templates/user_management/index.html
{% extends './layout.html' %}
{% block body %}
	{% for message in messages %}
		<h5 class="error">{{ message }}</h5>
	{% endfor %}
	<h1>Login or Register</h1>
	<div id="registration-form">
		<form action="{% url 'user_management:create' %}" method="post">
			{% csrf_token %}
			<label>Alias: </label>
			<input type="text" name="alias" placeholder="Vanilla Ice">
			<label>First Name:</label>
			<input type="text" name="first-name" placeholder="Robert">
			<label>Last Name:</label>
			<input type="text" name="last-name" placeholder="Van Winkle">
			<label>Email:</label>
			<input type="text" name="email" placeholder="ice@ice.baby">
			<label>Password:</label>
			<input type="password" name="password">
			<p>*Password must be at least 8 characters.</p>
			<label>Confirm Password:</label>
			<input type="password" name="confirm">
			<input type="submit" name="Sign Up">
		</form>
	</div>
	<div id="login-form">
		<form action="{% url 'user_management:login' %}" method="post">
			{% csrf_token %}
			<label>Email:</label>
			<input type="text" name="email" placeholder="ice@ice.baby">
			<label>Password:</label>
			<input type="password" name="password">
			<input type="submit" value="Log In">
		</form>
	</div>
{% endblock %}

python_stack/django/level2/belt_reviewer/apps/user_management/templates/user_management/layout.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<meta charset="utf-8">
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'user_management/css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'user_management/css/skeleton.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'user_management/css/styles.css' %}">
	{% block head %}{% endblock %}
</head>
<body>
	{% block body %}{% endblock %}
</body>
</html>

python_stack/django/level2/belt_reviewer/apps/user_management/templates/user_management/user_details.html
{% extends '../book_review/layout.html' %}
{% block body %}

	{% if messages %}
		{% for message in messages %}
			<h5 class="error">{{ message }}</h5>
		{% endfor %}
	{% endif %}

	<h2>User Alias: {{ user_info.alias }}</h2>
	<p>Name: {{ user_info.first_name }} {{ user_info.last_name }}</p>
	<p>Email: {{ user_info.email }}</p>
	<p>Total Reviews: {{ user_info.total_reviews }}</p>
	<p>Posted reviews about the following books:</p>
	<ul>
		{% for book in user_info.books %}
			<li><a href="{% url 'book_review:show' book.id %}">{{ book.title }}</a></li>
		{% empty %}
			<li>Looks like you haven't written any reviews!</li>
		{% endfor %}
	</ul>

{% endblock %}